Application.ensure_all_started(:tzdata)
Application.ensure_all_started(:ecto)
# Application.ensure_all_started(Scrooge.Repo, :temporary)
{:ok, _} = ScroogeWeb.Endpoint.start_link()
{:ok, _} = Scrooge.Repo.start_link()
Ecto.Adapters.SQL.Sandbox.mode(Scrooge.Repo, :manual)
ExUnit.start()
